apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfa-demo
  template:
    metadata:
      labels:
        app: mfa-demo
    spec:
      containers:
        - name: mfa-demo
          image: ghcr.io/gianfrancococchieri-commits/mfa-demo:latest
          imagePullPolicy: Always
          ports:
           - containerPort: 3000
